### ISSUE TITLE
Add me to this repository

### ISSUE THREAD

**Issue by arun-luup** [chintakindisantosh/project-X#1]
Hi Santosh, can you pls add me to this repository?

**Comment by chintakindisantosh** [comment]
Arun, Looks like I have no access to add others. To do I guess there are some monthly charges.

**Comment by chintakindisantosh** [comment]
You should be able to download the code but not commit new changes

**Comment by chintakindisantosh** [comment]
I have sent a request...

**Comment by arun-luup** [comment]
ok da....let us ensure that we spend quality time on this project...let us build a website for buying/renting properties...We will be able to work on API framework like Guzzlehttp and connect to Zoopla.com, findaproperty.com etc.

**Comment by chintakindisantosh** [comment]
Sure, Arun.. couple of things I've learnt now...
Here in Github we can create task cards and track the progress.
And I was thinking of Bugzilla for tracking any bugs but I just realised that Github provides it already, that's amazing.

**Comment by chintakindisantosh** [comment]
I've created sample cards and wiki page. Please let me know if you are able to see them?

**Comment by arun-luup** [comment]
i'm unable to see the cards da....for time being create issues for each task and we can track progress via boards
